name: paydunya
homepage: https://github.com/devmagatte/paydunya
description: Un package qui implément les methodes de paiement de paydunya.
version: 1.0.2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
